# Generated by Django 2.0.5 on 2018-05-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='day',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(default='', max_length=200),
        ),
    ]
